### ISSUE TITLE
Allow to push to tag only or to different branch

### ISSUE THREAD

**Issue by foxriver76** [AlCalzone/release-script#143]
For the js-controller project we currently have a protected master branch which does not allow direct pushing. Thus we need to push to a different branch first/or just to the tag and then create a PR via GH actions from there on.

As it would be great if we can still use the releas script for version managing, it would be desireable to have this feature in here.

**Comment by AlCalzone** [comment]
AFAIK this should work if the release script would push just the tag and discard the commit on the branch. Since the tags it creates are annotated tags, they can be used almost standalone and don't point to a specific commit. The release workflow should pick them up, the only downside is that all tags would be like this:
![grafik](https://github.com/AlCalzone/release-script/assets/17641229/08dacac6-fc20-413c-bb63-88157b7b03b6)

The CI workflow could then merge that tag into `master`, so it looks like this:
![grafik](https://github.com/AlCalzone/release-script/assets/17641229/05643574-f80f-4865-8384-46ba3288f7c1)

Github also understands this and shows which commit is part of the release:
![grafik](https://github.com/AlCalzone/release-script/assets/17641229/32b0f049-bc91-439e-bf21-8e918c1fe613)
